### PR TITLE
Created a border color when a view is active.

### PR DESCRIPTION
**Pull request by jrosen081**
I updated the view to add functionality for #5. This will allow the user to give a border color in ItemAppearance. It also adds the functionality in ItemView that will display the border when it is active.

### CODE REVIEW

**Comment by jrosen081** [comment]
I also added support for #4. Now it will autoresize if that value is set to true. By default, it is set to false.

**Comment by shima11** [comment]
Thank you for your PR

**Comment by shima11** [comment]
LGTM!

**Comment by WooD1k** [comment]
This pull request has been merged, but if install via cocoapods then borderColor parameter is not available

**Pull request merged**
